[package]
name = "talonite"
version = "0.1.0"
edition = "2021"
authors = ["Adarsh Vengarathodi <hello@adarshv.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
rand = "0.8.5"
termion = "2.0.1"
